feat(request): allow to use a boolean for trustProxy
adonisjs/http-server pull request #76
Opened 2023-10-05 21:18 UTC by RomainLanz

Hey there! 👋🏻 

This PR adds testing around the `trustProxy` settings.
It also allows us to define a boolean to accept or deny all proxies.

We could also accept to receive a string that will be compiled on the fly. It will be slower than pre-computing the value, so I am not sure to add that feature.

2023-10-06 04:13 UTC, thetutlage commented
Can we do this normalization inside the `defineConfig` method? That way we will avoid creating a new function to wrap boolean for each request and the validation of the property will happen at the time of consuming the config?

2023-10-06 12:11 UTC, RomainLanz commented
It should be good! I have also added handling for compiling on-the-fly any string given.

2023-10-11 11:24 UTC, thetutlage requested changes

2023-10-11 11:24 UTC, thetutlage commented on src/types/request.ts
> +  trustProxy: ((address: string, distance: number) => boolean) | (() => boolean)
Any reason we want to allow a function that does not accept any parameters? 

If its related to the following line

```
normalizedConfig.trustProxy = () => tpValue
```

Then we should fix the function vs allowing another function type.

```ts
normalizedConfig.trustProxy = (_, __) => tpValue
```

2023-10-17 03:55 UTC, merged